# Global configuration
base_path = "assets/sounds/"

# ==========================================
# Water
# ==========================================
[Water.Rain]
file = "rain.ogg"
volume = 0.5
icon = "ğŸŒ§ï¸"
url = "https://github.com/AnonMiraj/Tanin/raw/refs/heads/main/assets/sounds/rain.ogg"

[Water.Thunderstorm]
file = "storm.ogg"
volume = 0.5
icon = "â›ˆï¸"
url = "https://github.com/AnonMiraj/Tanin/raw/refs/heads/main/assets/sounds/storm.ogg"

[Water.Ocean_Waves]
file = "waves.ogg"
volume = 0.5
icon = "ğŸŒŠ"
url = "https://github.com/AnonMiraj/Tanin/raw/refs/heads/main/assets/sounds/waves.ogg"

[Water.Flowing_Stream]
file = "stream.ogg"
volume = 0.5
icon = "ğŸ’§"
url = "https://github.com/AnonMiraj/Tanin/raw/refs/heads/main/assets/sounds/stream.ogg"

[Water.Boat_Ambiance]
file = "boat.ogg"
volume = 0.5
icon = "â›µ"
url = "https://github.com/AnonMiraj/Tanin/raw/refs/heads/main/assets/sounds/boat.ogg"

# ==========================================
# Nature
# ==========================================
[Nature.Birds_Chirping]
file = "birds.ogg"
volume = 0.5
icon = "ğŸ¦"
url = "https://github.com/AnonMiraj/Tanin/raw/refs/heads/main/assets/sounds/birds.ogg"

[Nature.Night_Crickets]
file = "summer-night.ogg"
volume = 0.5
icon = "ğŸŒ™"
url = "https://github.com/AnonMiraj/Tanin/raw/refs/heads/main/assets/sounds/summer-night.ogg"

[Nature.Wind_Blowing]
file = "wind.ogg"
volume = 0.5
icon = "ğŸ’¨"
url = "https://github.com/AnonMiraj/Tanin/raw/refs/heads/main/assets/sounds/wind.ogg"

# ==========================================
# Urban
# ==========================================
[Urban.Coffee_Shop]
file = "coffee-shop.ogg"
volume = 0.5
icon = "â˜•"
url = "https://github.com/AnonMiraj/Tanin/raw/refs/heads/main/assets/sounds/coffee-shop.ogg"

[Urban.City_Traffic]
file = "city.ogg"
volume = 0.5
icon = "ğŸ™ï¸"
url = "https://github.com/AnonMiraj/Tanin/raw/refs/heads/main/assets/sounds/city.ogg"

[Urban.Train]
file = "train.ogg"
volume = 0.5
icon = "ğŸš‚"
url = "https://github.com/AnonMiraj/Tanin/raw/refs/heads/main/assets/sounds/train.ogg"

# ==========================================
# Warmth
# ==========================================
[Warmth.Fireplace]
file = "fireplace.ogg"
volume = 0.5
icon = "ğŸ”¥"
url = "https://github.com/AnonMiraj/Tanin/raw/refs/heads/main/assets/sounds/fireplace.ogg"

# ==========================================
# Ambient Noise
# ==========================================
["Ambient Noise".White_noise]
file = "white-noise.ogg"
volume = 0.5
icon = "ğŸ“»"
url = "https://github.com/AnonMiraj/Tanin/raw/refs/heads/main/assets/sounds/white-noise.ogg"

["Ambient Noise".Pink_noise]
file = "pink-noise.ogg"
volume = 0.5
icon = "ğŸµ"
url = "https://github.com/AnonMiraj/Tanin/raw/refs/heads/main/assets/sounds/pink-noise.ogg"
